package campaigns

type SmsEventsEnum string
type CampaignStatusSelectionEnum string
type CampaignStateEnum string
type CampaignStateGetEnum string
type CampaignStatusPaymentEnum string
type RelevantKeywordsModeEnum string
type DailyBudgetModeEnum string
type CampaignFundsEnum string
type CampaignTypeEnum string
type CampaignTypeGetEnum string
type CampaignFieldEnum string
type TextCampaignFieldEnum string
type MobileAppCampaignFieldEnum string
type DynamicTextCampaignFieldEnum string
type TextCampaignSearchStrategyTypeEnum string
type TextCampaignNetworkStrategyTypeEnum string
type MobileAppCampaignSearchStrategyTypeEnum string
type MobileAppCampaignNetworkStrategyTypeEnum string
type DynamicTextCampaignSearchStrategyTypeEnum string
type DynamicTextCampaignNetworkStrategyTypeEnum string
type TextCampaignSettingsEnum string
type TextCampaignSettingsGetEnum string
type MobileAppCampaignSettingsEnum string
type MobileAppCampaignSettingsGetEnum string
type DynamicTextCampaignSettingsEnum string
type DynamicTextCampaignSettingsGetEnum string
