package dynamictextadtargets

type WebpageFieldEnum string
type WebpageConditionOperandEnum string
type WebpageTypeEnum string
type WebpageStateSelectionEnum string
type StringConditionOperatorEnum string
