package bidmodifiers

type BidModifierTypeEnum string
type BidModifierToggleTypeEnum string
type BidModifierLevelEnum string
type BidModifierFieldEnum string
type MobileAdjustmentFieldEnum string
type DemographicsAdjustmentFieldEnum string
type RetargetingAdjustmentFieldEnum string
